/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * add_books.java
 *
 * Created on 13 Jul, 2015, 9:05:14 AM
 */

package library_management;

/**
 *
 * @author abhilasha
 */import java.sql.*;
import javax.swing.JOptionPane;
public class add_books extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
int s=0;
    /** Creates new form add_books */
    public  add_books() {
        initComponents();
        setSize(400,407);
        setResizable(false);

        try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
           rs=stmt.executeQuery("select * from book");
           while(rs.next())
           {
               s=rs.getInt("ID");
           }
jTextField1.setText(""+(s+1));
jTextField1.setEditable(false);
}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Books");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 9, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 70, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 70, 240, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 80, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 120, 240, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Author Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Publisher");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 70, 17);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 170, 240, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 220, 240, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 60, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(130, 270, 240, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 14));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 330, 70, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter-background-17.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String book_name=jTextField2.getText();
String author_name=jTextField3.getText();
String publisher=jTextField4.getText();
String quantity=jTextField5.getText();

if(book_name.equals("")||author_name.equals("")||publisher.equals("")||quantity.equals(""))
{
 JOptionPane.showMessageDialog(null,"Enter all fields");

}

else
{


       try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();

stmt.executeUpdate("insert into book(book_name,author_name,publisher,quantity) values('"+book_name+"','"+author_name+"','"+publisher+"','"+quantity+"')");
          new book_details().setVisible(true);

         
       }
     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
} // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
