/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * book_issue.java
 *
 * Created on 13 Jul, 2015, 5:27:05 PM
 */

package library_management;

/**
 *
 * @author abhilasha
 */import java.util.*;
 //import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;

public class book_issue extends javax.swing.JFrame {
Connection conn;
Statement stmt;
Statement stmt1;
ResultSet rs;
int c=0;
  String quantity;
  int qty;
    /** Creates new form book_issue */
    public book_issue() {
        initComponents();
        setSize(470,500);
        setResizable(false);
        //Date a=new Date();
       // System.out.println(a);
        GregorianCalendar g=new  GregorianCalendar();
     jTextField4.setText(  g.get(Calendar.DATE)+"/"+g.get(Calendar.MONTH)+"/"+g.get(Calendar.YEAR));
    g.add(Calendar.DATE,20);
    jTextField5.setText(g.get(Calendar.DATE)+"/"+g.get(Calendar.MONTH)+"/"+g.get(Calendar.YEAR));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Issue");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 0, 220, 56);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 80, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 60, 260, 20);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 70, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 130, 260, 20);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Author Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 110, 29);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 260, 260, 20);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Issue Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 310, 90, 29);

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Expiry Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 380, 100, 29);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 320, 260, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(130, 380, 260, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 420, 120, 40);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 200, 100, 29);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(130, 200, 260, 20);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter-background-17.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String student_id=jTextField1.getText();
String book_id=jTextField2.getText();
String book_name=jTextField6.getText();
String author_name=jTextField3.getText();
String issue_date=jTextField4.getText();
String expiry_date=jTextField5.getText();
String fine="0";
     try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");

             stmt1=conn.createStatement();
          rs=stmt1.executeQuery("select * from book");
           while(rs.next())
           {
               String a=String.valueOf(rs.getInt("ID"));
              
               if(a.equals(book_id))
               {
                   qty=Integer.parseInt(rs.getString("quantity"));
                   System.out.println(qty);
                   if(qty==0)
                       c=1;
               
               }
           }
          if(c==0)
              qty--;

                  quantity=String.valueOf(qty);
                  System.out.println(quantity);
stmt1.executeUpdate("update book set quantity="+"'"+quantity+"'"+" where ID="+book_id);

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }

if(c==0)
{
     try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
         
stmt.executeUpdate("insert into book_issue(student_id,book_id,book_name,author_name,issue_date,expiry_date,fine) values('"+student_id+"','"+book_id+"','"+book_name+"','"+author_name+"','"+issue_date+"','"+expiry_date+"','"+fine+"')");


}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }     }
else
{
    JOptionPane.showMessageDialog(null,"No books Found");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField6.setText("");


}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
