/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * book_details.java
 *
 * Created on 13 Jul, 2015, 9:02:15 AM
 */

package library_management;

/**
 *
 * @author abhilasha
 */
import java.awt.print.PrinterException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class book_details extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
String arr[]=new String[100];
    /** Creates new form book_details */
    public book_details() {
        initComponents();
        validate();
        setSize(1250,700);
        setResizable(false);
        jTable1.setRowHeight(30);
       
          try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from book");
          while(rs.next())
          {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=rs.getString("book_name");
              c++;
              arr[c]=rs.getString("author_name");
              c++;
              arr[c]=rs.getString("publisher");
              c++;
              arr[c]=rs.getString("Quantity");


                 DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(arr);





          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Traditional Arabic", 1, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book-id", "Book Name", "Author Name", "Publisher", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 1140, 410);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selected book-id:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 560, 140, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 560, 230, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 610, 130, 35);

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton2.setText("Delete");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 610, 120, 40);

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton3.setText("Update");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 610, 120, 35);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 48));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Details");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 10, 300, 90);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 560, 110, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(800, 560, 240, 20);

        jButton4.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1060, 550, 110, 37);

        jButton5.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton5.setText("View all");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(880, 620, 130, 37);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1083, 90, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter-background-17.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentShown(evt);
            }
        });
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1280, 1040);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
int row=jTable1.getSelectedRow();
System.out.println(row);
String book_id=model.getValueAt(row, 0).toString();
jTextField1.setText(book_id);   // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int book_id=Integer.parseInt(jTextField1.getText());
        int p=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete book-id="+book_id+"?");

     if(p==0)
     {


        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
model.removeRow(jTable1.getSelectedRow());


      try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
            stmt.executeUpdate("delete * from book where ID="+book_id);

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
    int book_id=Integer.parseInt(jTextField1.getText());
        int a=evt.getKeyCode();
        int row=jTable1.getSelectedRow();
     System.out.println(a);
     if(a==10)
     {
         String book_name=String.valueOf(jTable1.getValueAt(row, 1));
String author_name=String.valueOf(jTable1.getValueAt(row, 2));
String publisher=String.valueOf(jTable1.getValueAt(row, 3));
String quantity=String.valueOf(jTable1.getValueAt(row, 4));


int p=JOptionPane.showConfirmDialog(null,"Are you sure you want to update book-id="+book_id+"?");

     if(p==0)
     {



  try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          stmt.executeUpdate("update book set book_name="+"'"+book_name+"'"+" where ID="+book_id);
           stmt.executeUpdate("update book set author_name="+"'"+author_name+"'"+" where ID="+book_id);
            stmt.executeUpdate("update book set publisher="+"'"+publisher+"'"+" where ID="+book_id);
             stmt.executeUpdate("update book set quantity="+"'"+quantity+"'"+" where ID="+book_id);
}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }

     }}


        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new add_books().setVisible(true);
     dispose();
    
 /*DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
 jTable1.setModel(model);*/

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
 new book_details().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jLabel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentShown
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jLabel1ComponentShown

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
              DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);

        String book_name=jTextField2.getText();
       System.out.println(book_name);
            try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from book");
          while(rs.next())
          {
               if(book_name.equalsIgnoreCase(rs.getString("book_name")))

              {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=book_name;
              c++;
              arr[c]=rs.getString("author_name");
              c++;
              arr[c]=rs.getString("publisher");
              c++;
              arr[c]=rs.getString("Quantity");


                // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(arr);





          }}

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from book");
          while(rs.next())
          {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=rs.getString("book_name");
              c++;
              arr[c]=rs.getString("author_name");
              c++;
              arr[c]=rs.getString("publisher");
              c++;
              arr[c]=rs.getString("Quantity");


                
        model.addRow(arr);





          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
          jTable1.print();
        } catch (PrinterException pe) {
          System.err.println("Error printing: " + pe.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables




}
