/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * change_password.java
 *
 * Created on 14 Jul, 2015, 9:54:34 AM
 */

package library_management;

/**
 *
 * @author abhilasha
 */import java.sql.*;
import javax.swing.*;
public class change_password extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;
    int id;

    /** Creates new form change_password */
    public change_password(String a) {
        initComponents();
        setSize(470,340);
        setResizable(false);
        id=Integer.parseInt(a);
        jTextField1.setText(""+id);
        jTextField1.setEditable(false);





    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 240, 60);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 80, 29);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 80, 240, 20);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Previous Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 160, 29);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 140, 240, 20);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 140, 29);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(190, 200, 240, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 260, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_plain_1280x960.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String old_password=String.valueOf(jPasswordField1.getPassword());
String new_password=String.valueOf(jPasswordField2.getPassword());

   try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
            rs=stmt.executeQuery("select * from student");
            while(rs.next())
            {
                int student_id=rs.getInt("ID");
                if(student_id==id)
                {
                    String password=rs.getString("password");
                    if(password.equals(old_password))
                    {
                        stmt.executeUpdate("update student set password="+"'"+new_password+"'"+" where ID="+id);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Enter correct Password");
                    }
                }




            }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change_password("3").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
