/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * edit_details.java
 *
 * Created on 13 Jul, 2015, 10:08:44 PM
 */

package library_management;

/**
 *
 * @author abhilasha
 */
import java.sql.*;
public class edit_details extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;
    int id;
    /** Creates new form edit_details */
    public edit_details(String a) {
        
         id=Integer.parseInt(a);

        initComponents();
        setSize(420,350);
        setResizable(false);
          try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
rs=stmt.executeQuery("select * from student");
           while(rs.next())
           {
               int s=rs.getInt("ID");
               if(s==id)
               {
                   jTextField1.setText(rs.getString("name"));
                    jTextField2.setText(rs.getString("roll_no"));
                     jTextField3.setText(rs.getString("class"));

               }
           }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 60, 29);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 90, 250, 20);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Roll No");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 70, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 150, 250, 20);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Class");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 80, 29);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 210, 250, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 270, 110, 30);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 20, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_plain_1280x960.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name=jTextField1.getText();
String roll_no=jTextField2.getText();
String classs=jTextField3.getText();
  try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
 stmt.executeUpdate("update student set name="+"'"+name+"'"+" where ID="+id);

stmt.executeUpdate("update student set roll_no="+"'"+roll_no+"'"+" where ID="+id);
stmt.executeUpdate("update student set class="+"'"+classs+"'"+" where ID="+id);
}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_details("3").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
