/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * member_details.java
 *
 * Created on 13 Jul, 2015, 2:17:01 PM
 */

package library_management;

/**
 *
 * @author abhilasha
 */
import java.awt.print.PrinterException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class member_details extends javax.swing.JFrame {

Connection conn;
Statement stmt;
ResultSet rs;
int p=1;
String arr[]=new String[100];
    /** Creates new form member_details */
    public member_details() {
        initComponents();
        validate();
        setSize(1250,700);
        setResizable(false);
        jTable1.setRowHeight(30);

          try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from student");
          while(rs.next())
          {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=rs.getString("name");
              c++;
              arr[c]=rs.getString("class");
              c++;
              arr[c]=rs.getString("roll_no");
             


                 DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(arr);
         p++;




          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Traditional Arabic", 1, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student-id", "Student Name", "Class", "Roll-no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 100, 1020, 430);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selected Student-id:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 550, 190, 29);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 550, 310, 20);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton1.setText("View books issued");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 620, 200, 37);

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 620, 150, 37);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 550, 90, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(810, 550, 160, 20);

        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(990, 540, 100, 30);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student roll-no");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 590, 130, 29);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(810, 590, 160, 20);

        jButton4.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(990, 580, 100, 30);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 48));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 20, 350, 50);

        jButton5.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jButton5.setText("View all");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(990, 630, 100, 30);

        jButton6.setText("print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(993, 70, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter-background-17.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
int row=jTable1.getSelectedRow();
System.out.println(row);
String student_id=model.getValueAt(row, 0).toString();
jTextField1.setText(student_id);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int student_id=Integer.parseInt(jTextField1.getText());
        int p=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete student-id="+student_id+"?");

     if(p==0)
     {


        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
model.removeRow(jTable1.getSelectedRow());


      try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
            stmt.executeUpdate("delete * from student where ID="+student_id);

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        String student_id=jTextField2.getText();
       System.out.println(student_id);
        try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from student");
          while(rs.next())
          {
              if(student_id.equals(String.valueOf(rs.getInt("ID"))))
              {
              int c=0;

              arr[c]=student_id;
              c++;
              arr[c]=rs.getString("name");
              c++;
              arr[c]=rs.getString("class");
              c++;
              arr[c]=rs.getString("roll_no");



                 //DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

                 model.addRow(arr);



              }

          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);

        String roll_no=jTextField3.getText();
       System.out.println(roll_no);
        try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from student");
          while(rs.next())
          {
              if(roll_no.equals(rs.getString("roll_no")))

              {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=rs.getString("name");
              c++;
              arr[c]=rs.getString("class");
              c++;
              arr[c]=roll_no;



                 //DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

                 model.addRow(arr);



              }

          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
          try
       {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           conn=DriverManager.getConnection("jdbc:odbc:library_management");
           System.out.println("connected");
           stmt=conn.createStatement();
          rs=stmt.executeQuery("select * from student");
          while(rs.next())
          {
              int c=0;

              arr[c]=String.valueOf(rs.getInt("ID"));
              c++;
              arr[c]=rs.getString("name");
              c++;
              arr[c]=rs.getString("class");
              c++;
              arr[c]=rs.getString("roll_no");




        model.addRow(arr);
         p++;




          }

}

     catch(SQLException se)
     {
System.out.println(se);
     }

     catch(ClassNotFoundException ce)
     {
System.out.println(ce);
     }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new issued_books(jTextField1.getText()).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
          jTable1.print();
        } catch (PrinterException pe) {
          System.err.println("Error printing: " + pe.getMessage());
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
